"""empty message

Revision ID: 4c5fbe0e682c
Revises: 
Create Date: 2021-10-15 11:30:33.993354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5fbe0e682c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('partner_id'),
    sa.UniqueConstraint('partner_name')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner_name'], ['partner.partner_name'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('partner')
    # ### end Alembic commands ###
